### ISSUE TITLE
Unable to send mail with lambda

### ISSUE THREAD

**Issue by ranavikas007** [wweiss/aws-serverless-sns-email-forms#3]
Hello William,

While trying your code with cloud-formation. I'm getting error in running lambda function with test event.

Test message json:
```
{
  "body": "Hello Vikas",
  "subject": "Lambda Fn"
}
```
Error:
```
{
  "errorType": "SyntaxError",
  "errorMessage": "Unexpected token H in JSON at position 0",
  "trace": [
    "SyntaxError: Unexpected token H in JSON at position 0",
    "    at JSON.parse (<anonymous>)",
    "    at Runtime.a.handler (/var/task/sns-email-forms.js:127:8620)",
    "    at Runtime.handleOnce (/var/runtime/Runtime.js:66:25)"
  ]
}
```

Do we need to have any sample template in s3 before using it?
Do you share what is expected template message?

**Comment by ranavikas007** [comment]
I'm able to using following message format:
`{
  "form": "example",
  "from": "joe@dirt.io",
  "subject": "Airplane waste management",
  "messageModel": {
    "name": "Joe Doe",
    "message": "I just found it there..."
  }
}` 

But after trying with postman on API gateway endpoint:
`{
    "missingFields": [
        "token"
    ],
    "invalidFields": []
}`
How can I pass reCaptcha sitekey in POST call?

**Comment by wweiss** [comment]
Hi!

First, I have to apologize - I was called away onto other projects before I could really complete the documentation on this one the way I would like!

Now, regarding the issue with the "token".  If you have enabled the use of Google's reCaptcha, you will need to use JS on the form and provide a callback to reCaptcha to receive the response token before submitting the form.  Once you have the token (which proves they completed the catpcha), you include it in your message like this:

`{ "form": "example", "from": "joe@dirt.io", "subject": "Airplane waste management", "token": "<TOKEN FROM GOOGLE>" "messageModel": { "name": "Joe Doe", "message": "I just found it there..." } }`

You can find more information about how this works [here](https://developers.google.com/recaptcha/docs/display#configuration). 

If you are using React for the frontend, you might also find this component helpful (I have!): [reaptcha](https://www.npmjs.com/package/reaptcha)

I've created an issue to complete the documentation: #4

**Comment by wweiss** [comment]
As a side note, if you want to simply check your configuration using Postman without worrying about the reCaptcha token, just go to the deployed Lambda function in your console and under **Environment variables**  change the `RECAPTCHA_ENABLED` to `false`.

**Comment by wweiss** [comment]
@mention #4

**Comment by wweiss** [comment]
Please let me know if you need any further help!

**Comment by ranavikas007** [comment]
@wweiss thanks for your response, with reCaptca I'm able to send mail using sns.

But with ReCaptcha enable, and properly generating token on client side as per https://developers.google.com/recaptcha/. I'm getting following logical errors:

Without token:
{ "missingFields": [ "token" ], "invalidFields": [] }
![image](https://user-images.githubusercontent.com/43035245/80404002-28644a80-88de-11ea-86e5-728cdc286fc8.png)

With Token:
![image](https://user-images.githubusercontent.com/43035245/80404039-36b26680-88de-11ea-8548-d505ff4c312d.png)

I tried putting it on all places it doesn't work.

I've tested with https://github.com/wweiss/aws-serverless-sns-email-forms/blob/master/test/example.schema.json as well as updated example.schema.json as follows:
`{
  "required": ["name", "message", "email", "token"],
  "properties": {
    "name": {
      "type": "string"
    },
    "message": {
      "type": "string"
    },
    "email": {
      "type": "string"
    },
    "token": {
      "type": "string"
    }
  },
  "additionalProperties": false
}`

**Comment by wweiss** [comment]
I'm sorry to hear you're still having issues.  The `"invalidFields":["token"]` indicates that the token was properly sent, but Google rejected it.  

I would look in your logs for the phrase `ReCAPTCHA failed with error` to find out why Google rejected it.

**Comment by ranavikas007** [comment]
@wweiss Sorry for late response, I was able to follow google captcha docs and PIs able to get APIs working with POSTMAN.
But from a hosted website I'm getting CORs error. I was able to manually edit/update CORs header in API gateway and make it work. But feel like if we can handle CORs at app level that would be great.

**Comment by wweiss** [comment]
Yeah, I tend to run this behind cloudfront with the rest of the site.  Because of that, I sidestep the CORS issue.  However, I understand that this isn't always possible.  I've created issue #5 to address that.
