### ISSUE TITLE
Add CORS support

### ISSUE THREAD

**Issue by wweiss** [wweiss/aws-serverless-sns-email-forms#5]
Add builtin support for handling CORS.

**Comment by ranavikas007** [comment]
@wweiss this will be helpful. Thanks in advance.

**Comment by wweiss** [comment]
This functionality is now available as of the v0.3.1 release.

**Comment by ranavikas007** [comment]
@wweiss after this patch I'm seeing JSON parsing error from app side. This is happening for both CORs flag set as true or false.

`{
  "errorType": "SyntaxError",
  "errorMessage": "Unexpected end of JSON input",
  "trace": [
    "SyntaxError: Unexpected end of JSON input",
    "    at JSON.parse (<anonymous>)",
    "    at /var/task/sns-email-forms.js:217:194499",
    "    at Generator.next (<anonymous>)",
    "    at /var/task/sns-email-forms.js:217:191948",
    "    at new Promise (<anonymous>)",
    "    at S (/var/task/sns-email-forms.js:217:191693)",
    "    at Runtime.q [as handler] (/var/task/sns-email-forms.js:217:194450)",
    "    at Runtime.handleOnce (/var/runtime/Runtime.js:66:25)"
  ]
}`

This is the TEST event used:
`{
    "form": "example",
    "from": "joe@dirt.io",
    "subject": "Airplane waste management",
    "token": "03AGdBq26J96_oeEzXHt84j18poKIX1Bs0nxzRJzTDbwnLqvsQr_binKr2nskBBh3grZi3VAUP93zu9-biBTAqV23amvxn1tDEZ3yk0t3_ojCgB5cse9VMAygi6tjDP9_Vtnc8FmnH49b_Vc-cGrTx6ZS0Tdd-mE4ON5q1UItIkqd-7Cvfw04HOIXOr7F7VlDlqth_x8rYlEjnS0eCTet2dl5phhsNtDsMBQeFb3rablbF8fwreEfaziU_r_AMgvjkFPJUyZ_PusbqE6-FBI7PseVivg7tQ4cMW5ebYQl5fi91AcLrxIusQ_7ryVoeB3_ZvNNjPuo04yV8wQyiGDz1jOrkRu_Y3pcQic5i279KqX8lnabYlHJ9EFP3DCPsyNmf6n63BA7HV5lY",
    "messageModel": {
      "name": "Joe Doe",
      "message": "I just found it there...",
      "email": "joe@dirt.io"
    }
}`

**I feel like after enabling CORS in API gateway side, it doesn't pass JSON as before.**
