### ISSUE TITLE
JSON parsing error after latest CORs enable patch 

### ISSUE THREAD

**Issue by ranavikas007** [wweiss/aws-serverless-sns-email-forms#6]
@wweiss after this patch I'm seeing JSON parsing error from app side. This is happening for both CORs flag set as true or false.

{ "errorType": "SyntaxError", "errorMessage": "Unexpected end of JSON input", "trace": [ "SyntaxError: Unexpected end of JSON input", " at JSON.parse (<anonymous>)", " at /var/task/sns-email-forms.js:217:194499", " at Generator.next (<anonymous>)", " at /var/task/sns-email-forms.js:217:191948", " at new Promise (<anonymous>)", " at S (/var/task/sns-email-forms.js:217:191693)", " at Runtime.q [as handler] (/var/task/sns-email-forms.js:217:194450)", " at Runtime.handleOnce (/var/runtime/Runtime.js:66:25)" ] }

This is the TEST event used:
{ "form": "example", "from": "joe@dirt.io", "subject": "Airplane waste management", "token": "03AGdBq26J96_oeEzXHt84j18poKIX1Bs0nxzRJzTDbwnLqvsQr_binKr2nskBBh3grZi3VAUP93zu9-biBTAqV23amvxn1tDEZ3yk0t3_ojCgB5cse9VMAygi6tjDP9_Vtnc8FmnH49b_Vc-cGrTx6ZS0Tdd-mE4ON5q1UItIkqd-7Cvfw04HOIXOr7F7VlDlqth_x8rYlEjnS0eCTet2dl5phhsNtDsMBQeFb3rablbF8fwreEfaziU_r_AMgvjkFPJUyZ_PusbqE6-FBI7PseVivg7tQ4cMW5ebYQl5fi91AcLrxIusQ_7ryVoeB3_ZvNNjPuo04yV8wQyiGDz1jOrkRu_Y3pcQic5i279KqX8lnabYlHJ9EFP3DCPsyNmf6n63BA7HV5lY", "messageModel": { "name": "Joe Doe", "message": "I just found it there...", "email": "joe@dirt.io" } }

I feel like after enabling CORS in API gateway side, it doesn't pass JSON as before.

**Comment by wweiss** [comment]
Hi,

Again, sorry you are having issues!  I've tried to replicate your result with postman by doing the following:

- Making a request with your test event as-is and no` Origin` header (CORS enabled)
  - Result: 400 with an `InvalidField` on the `email` property (my schema didn't have it)
- Same setup, but without the `email` property on the event
  - Result: 200
- Same setup, but with the `Origin` header set to `null`
  - Result: 200

It makes me think you may have an error in your schema file.  Is it possible to share them here?

Thanks!

**Comment by wweiss** [comment]
On a side note, I just published v0.3.3 which includes much improved error handling and logging.  You might try upgrading and see if the location of the error becomes more obvious...

I've added instructions on how to adjust the logging level as well.

**Comment by wweiss** [comment]
Just wanted to ping this thread and see if this was resolved for you?

**Comment by wweiss** [comment]
I'm going to close this for now.  If you are still having problems, just ping this issue.
