### ISSUE TITLE
CORS doesn't seem to work without Access-Control-Allow-Methods header

### ISSUE THREAD

**Issue by secrnd** [wweiss/aws-serverless-sns-email-forms#9]
I'm getting:
Access to XMLHttpRequest at ....
from origin 'null' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: It does not have HTTP ok status.

In Chrome Version 83.0.4103.116 (Official Build) (64-bit)

Is there a way to configure SnsEmailForms to include the Access-Control-Allow-Methods header?

**Comment by wweiss** [comment]
Hi,

You really shouldn't need the allow methods header. Please, make sure you are sending the request via POST as specified and check if you are not sending additional headers that would trigger the preflight.  

However, if you are still having issues, I will need more information about how you are making your request and how you have configured the serverless app.

Thanks!

**Comment by secrnd** [comment]
You're right, Access-Control-Allow-Methods header is not required. I was using Axios and didn't stringify the post data. Thanks for the quick reply!
